# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef9def62c77e26674e1624f2f69d4b69dccb905771f16dc89229ae644fc8f0746678a6533bdac100e3779f35aeb6a0d72a22abea9b0313e96c05136bc2ef20f6

test:
  secret_key_base: 8b479a523bc1e80c08af6b5542aa6084f14281bafa46588ced1a077e86bce8e79e34e4ac795b0e8ee871384434c13bd0b5d1099cff5b4a6b41c186cb54c208bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
